version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "7777:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libs
      MYSQL_USER: muser
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_migrate
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel_network
    command: >
      sh -c "php artisan migrate:refresh && php artisan l5-swagger:generate"

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge