version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./lib-rest/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_network
    environment:
      - UID=${UID}
      - GID=${GID}

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7777:80"
    networks:
      - laravel_network
    depends_on:
      - app

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: laravel_migrate
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - laravel_network
    entrypoint: >
      sh -c "php artisan migrate:refresh &&
             php artisan l5-swagger:generate"
    environment:
      - UID=${UID}
      - GID=${GID}

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libs
      MYSQL_USER: muser
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
